#!/bin/tcsh

setenv CHEMICSROOTPATH  "/disk1/jonsta/dev/Chemics/"

#setenv PYTHONPATH {$PYTHONPATH}:{$CHEMICSROOTPATH}/APWS/APWS/APEndpoints:{$CHEMICSROOTPATH}/APWS/APWS
setenv PYTHONPATH {$CHEMICSROOTPATH}/APWS/APWS/APEndpoints:{$CHEMICSROOTPATH}/APWS/APWS
setenv PATH {$PATH}:{$CHEMICSROOTPATH}/APWS/APWS/bin

python startAP.py 
